### ISSUE TITLE
Lottery.staging.test.js AssertionError

### ISSUE THREAD

**Issue by SlothXGreaver** [PatrickAlphaC/hardhat-smartcontract-lottery-fcc#13]
When I run
`hh test --network rinkeby`
on my _Lottery.staging.test.js_ file, I get the following output:

```
 Lottery Unit Tests
    fulfillRandomWords
Setting up test...
Setting up Listener...
Entering Lottery...
Ok, time to wait...
WinnerPicked event fired!
AssertionError: expected '781901563946176163' to equal '791970612949076221'
    at FragmentRunningEvent.<anonymous> (/home/greaver/FullStack/hardhat-smartcontract-lottery-fcc/test/staging/Lottery.staging.test.js:49:38)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  showDiff: true,
  actual: '781901563946176163',
  expected: '791970612949076221',
  operator: 'strictEqual'
}
```
After the error, it hangs, until the Mocha 500 second timeout  in my _hardhat.config.js_ file kicks in with:
`Error: Timeout of 500000ms exceeded.`

My _Lottery.staging.test.js_ code is the same as Patrick's atm because I wanted it to work (mine is below this code commented out (not included here)...:
```
const { assert, expect } = require("chai");
const { getNamedAccounts, deployments, ethers, network } = require("hardhat");
const {
    developmentChains,
    networkConfig,
} = require("../../helper-hardhat-config");

developmentChains.includes(network.name)
    ? describe.skip
    : describe("Lottery Unit Tests", function () {
          let lottery, LotteryEntranceFee, deployer;

          beforeEach(async function () {
              deployer = (await getNamedAccounts()).deployer;
              lottery = await ethers.getContract("Lottery", deployer);
              lotteryEntranceFee = await lottery.getEntranceFee();
          });

          describe("fulfillRandomWords", function () {
              it("works with live Chainlink Keepers and Chainlink VRF, we get a random winner", async function () {
                  // enter the lottery
                  console.log("Setting up test...");
                  const startingTimeStamp = await lottery.getLatestTimeStamp();
                  const accounts = await ethers.getSigners();

                  console.log("Setting up Listener...");
                  await new Promise(async (resolve, reject) => {
                      // setup listener before we enter the raffle
                      // Just in case the blockchain moves REALLY fast
                      lottery.once("WinnerPicked", async () => {
                          console.log("WinnerPicked event fired!");
                          try {
                              // add our asserts here
                              const recentWinner =
                                  await lottery.getRecentWinner();
                              const lotteryState =
                                  await lottery.getLotteryState();
                              const winnerEndingBalance =
                                  await accounts[0].getBalance();
                              const endingTimeStamp =
                                  await lottery.getLatestTimeStamp();

                              await expect(lottery.getPlayer(0)).to.be.reverted;
                              assert.equal(
                                  recentWinner.toString(),
                                  accounts[0].address
                              );
                              assert.equal(lotteryState, 0);
                              assert.equal(
                                  winnerEndingBalance.toString(),
                                  winnerStartingBalance
                                      .add(lotteryEntranceFee)
                                      .toString()
                              );
                              assert(endingTimeStamp > startingTimeStamp);
                              resolve();
                          } catch (error) {
                              console.log(error);
                              reject(e);
                          }
                      });
                      // Then entering the lottery
                      console.log("Entering Lottery...");
                      await lottery.enterLottery({ value: lotteryEntranceFee });
                      console.log("Ok, time to wait...");
                      const winnerStartingBalance =
                          await accounts[0].getBalance();

                      // and this code WONT complete until our listener has finished listening!
                  });
              });
          });
      });
```
The failing math code on the assert at Lottery.staging.test.js:49:38, as you can see is:
`assert.equal(winnerEndingBalance.toString(), winnerStartingBalance.add(lotteryEntranceFee).toString());`

I am thinking the assert is being called before the promise is being returned, but do not know EXACTLY what is wrong.
The code runs and is error free, but the math isn't working out.

Does someone have a clue, unlike me?

**Comment by PatrickAlphaC** [comment]
And can you ask this in the discussions of the larger repo? Thanks!
https://github.com/smartcontractkit/full-blockchain-solidity-course-js/
