### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'length'), deployment of a contract.

### ISSUE THREAD

**Issue by tuagkcuf** [PatrickAlphaC/hardhat-smartcontract-lottery-fcc#152]
Error: ERROR processing H:\Programming\crypto\hardhat-smartcontract-lottery\deploy\01-deploy-raffle.js:
  TypeError: Cannot read properties of undefined (reading 'length')
      at getFrom (node_modules\hardhat-deploy\src\helpers.ts:1642:14)
      at _deploy (node_modules\hardhat-deploy\src\helpers.ts:537:9)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at runNextTicks (node:internal/process/task_queues:65:3)
      at listOnTimeout (node:internal/timers:526:9)
      at processTimers (node:internal/timers:500:7)
      at _deployOne (node_modules\hardhat-deploy\src\helpers.ts:934:16)
      at Object.module.exports [as func] (deploy\01-deploy-raffle.js:38:20)
      at DeploymentsManager.executeDeployScripts (node_modules\hardhat-deploy\src\DeploymentsManager.ts:1220:22)
      at DeploymentsManager.runDeploy (node_modules\hardhat-deploy\src\DeploymentsManager.ts:1053:5)
      at DeploymentsManager.executeDeployScripts (node_modules\hardhat-deploy\src\DeploymentsManager.ts:1223:19)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at runNextTicks (node:internal/process/task_queues:65:3)
      at listOnTimeout (node:internal/timers:526:9)
      at processTimers (node:internal/timers:500:7)
      at DeploymentsManager.runDeploy (node_modules\hardhat-deploy\src\DeploymentsManager.ts:1053:5)
      at Object.fixture (node_modules\hardhat-deploy\src\DeploymentsManager.ts:315:9)
      at Context.<anonymous> (test\unit\Raffle.test.js:13:15)

**Comment by nagrarohit** [comment]
are you still facing this issue @tuagkcuf

**Comment by abdullahtanvir11** [comment]
Look around the solved issues. Hopefully you will get the answer there.

**Comment by sohjag** [comment]
I got this error while trying to use readFileSync and writeFileSync. I used 
`const { readFileSync, writeFileSync } = require("node:fs")`

instead of just require('fs') and it worked for me

**Comment by Ab-verse** [comment]
I guess you missed namedAccounts on hadhat-config.js:

namedAccounts: {
        deployer: {
            default: 0, // here this will by default take the first account as deployer
        },
        player: {
            default: 1,
        },
    },

**Comment by coderharsx1122** [comment]
May be you have not used await keyword while destructuring deployer from get getNamedAccounts

`const { deployer } = await getNamedAccounts()`
