### ISSUE TITLE
Error: invalid address (argument="address", value={}, code=INVALID_ARGUMENT, version=address/5.7.0) (argument="vrfCoordinatorV2", value={}, code=INVALID_ARGUMENT, version=abi/5.7.0)

### ISSUE THREAD

**Issue by asalrahman** [PatrickAlphaC/hardhat-smartcontract-lottery-fcc#168]
Error: ERROR processing C:\Users\ACER\ether.js\Lottery\deploy\02-deploy-Lottery.js:
Error: invalid address (argument="address", value={}, code=INVALID_ARGUMENT, version=address/5.7.0) (argument="vrfCoordinatorV2", value={}, code=INVALID_ARGUMENT, version=abi/5.7.0)
    at Logger.makeError (C:\Users\ACER\ether.js\Lottery\node_modules\@ethersproject\logger\src.ts\index.ts:269:28)
    at Logger.throwError (C:\Users\ACER\ether.js\Lottery\node_modules\@ethersproject\logger\src.ts\index.ts:281:20)
    at Logger.throwArgumentError (C:\Users\ACER\ether.js\Lottery\node_modules\@ethersproject\logger\src.ts\index.ts:285:21)
    at AddressCoder.Coder._throwError (C:\Users\ACER\ether.js\Lottery\node_modules\@ethersproject\abi\src.ts\coders\abstract-coder.ts:68:16)
    at AddressCoder.encode (C:\Users\ACER\ether.js\Lottery\node_modules\@ethersproject\abi\src.ts\coders\address.ts:22:18)
    at C:\Users\ACER\ether.js\Lottery\node_modules\@ethersproject\abi\src.ts\coders\array.ts:71:19
    at Array.forEach (<anonymous>)
    at pack (C:\Users\ACER\ether.js\Lottery\node_modules\@ethersproject\abi\src.ts\coders\array.ts:54:12)
    at TupleCoder.encode (C:\Users\ACER\ether.js\Lottery\node_modules\@ethersproject\abi\src.ts\coders\tuple.ts:54:20)
    at AbiCoder.encode (C:\Users\ACER\ether.js\Lottery\node_modules\@ethersproject\abi\src.ts\abi-coder.ts:111:15)
    at DeploymentsManager.executeDeployScripts (C:\Users\ACER\ether.js\Lottery\node_modules\hardhat-deploy\src\DeploymentsManager.ts:1229:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at runNextTicks (node:internal/process/task_queues:65:3)
    at listOnTimeout (node:internal/timers:528:9)
    at processTimers (node:internal/timers:502:7)
    at DeploymentsManager.runDeploy (C:\Users\ACER\ether.js\Lottery\node_modules\hardhat-deploy\src\DeploymentsManager.ts:1059:5)
    at SimpleTaskDefinition.action (C:\Users\ACER\ether.js\Lottery\node_modules\hardhat-deploy\src\index.ts:438:5)
    at Environment._runTaskDefinition (C:\Users\ACER\ether.js\Lottery\node_modules\hardhat\src\internal\core\runtime-environment.ts:333:14)
    at Environment.run (C:\Users\ACER\ether.js\Lottery\node_modules\hardhat\src\internal\core\runtime-environment.ts:166:14)
    at SimpleTaskDefinition.action (C:\Users\ACER\ether.js\Lottery\node_modules\hardhat-deploy\src\index.ts:584:32)
error Command failed with exit code 1.

**Comment by PatrickAlphaC** [comment]
Can you:
1. Make this a discusson on the full repo? https://github.com/smartcontractkit/full-blockchain-solidity-course-js/
2. Follow this section for formatting questions? https://www.youtube.com/watch?t=19846&v=gyMwXuJrbJQ&feature=youtu.be
