### ISSUE TITLE
 Error: VM Exception while processing transaction

### ISSUE THREAD

**Issue by asalrahman** [PatrickAlphaC/hardhat-smartcontract-lottery-fcc#169]
1) Lottery
       enterLottery
         doesn't allow entrance when lottery is calculating:
     Error: VM Exception while processing transaction: reverted with custom error 'InvalidConsumer()'
    at VRFCoordinatorV2Mock.onlyValidConsumer (@chainlink/contracts/src/v0.8/mocks/VRFCoordinatorV2Mock.sol:72)
    at VRFCoordinatorV2Mock.requestRandomWords (@chainlink/contracts/src/v0.8/mocks/VRFCoordinatorV2Mock.sol:147)
    at Lottery.performUpkeep (contracts/Lottery.sol:104)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at runNextTicks (node:internal/process/task_queues:65:3)
    at listOnTimeout (node:internal/timers:528:9)
    at processTimers (node:internal/timers:502:7)
    at HardhatNode._mineBlockWithPendingTxs (node_modules\hardhat\src\internal\hardhat-network\provider\node.ts:1840:23)
    at HardhatNode.mineBlock (node_modules\hardhat\src\internal\hardhat-network\provider\node.ts:517:16)
    at EthModule._sendTransactionAndReturnHash (node_modules\hardhat\src\internal\hardhat-network\provider\modules\eth.ts:1532:18)

**Comment by asalrahman** [comment]
add this to deploy.js file

 if (developmentChains.includes(network.name)) {
    const vrfCoordinatorV2Mock = await ethers.getContract("VRFCoordinatorV2Mock")
    await vrfCoordinatorV2Mock.addConsumer(subscriptionId, lottery.address)
}

**Comment by akashgreninja** [comment]
I fixed it as well same solution as @asalrahman suggested 

https://github.com/PatrickAlphaC/hardhat-smartcontract-lottery-fcc/issues/171#issuecomment-1643423816
