### ISSUE TITLE
Getting error  TypeError: Cannot read properties of undefined (reading '0') in Lesson 9

### ISSUE THREAD

**Issue by coderharsx1122** [PatrickAlphaC/hardhat-smartcontract-lottery-fcc#182]
_Getting error in Lesson 9 Error: ERROR processing /root/hardhat-fcc/hardhat-smartcontract-lottery-fcc/deploy/01-deploy-raffle.js: TypeError: Cannot read properties of undefined (reading '0')_ 

**Error occurring at line 23 **
**Code at line 23** > `subscriptionId = transactionReceipt.events[0].args.subId`

### My 01-deploy-raffle.js file
`const { network, ethers } = require("hardhat")
const { networkConfig, developmenChain } = require("../helper-hardhat-conifg")
const {verify} = require("../utils/verify")

const VRF_SUB_FUND_AMOUNT = ethers.parseEther("30")

module.exports = async function ({ getNamedAccounts, deployments }) {
    const { deployer } = await getNamedAccounts()
    const { deploy, log } = deployments
    const chainId = network.config.chainId
    let vrfCoordinatorV2Address, subscriptionId

    if (developmenChain.includes(network.name)) {
        log("local network detected: deploying mocks....")

        const VRF2CordinatorV2Mock = await ethers.getContract("VRFCoordinatorV2Mock")
        vrfCoordinatorV2Address = VRF2CordinatorV2Mock.runner.address

        // console.log(VRF2CordinatorV2Mock)
        const transactionResponse = await VRF2CordinatorV2Mock.createSubscription()
        const transactionReceipt = await transactionResponse.wait(1)
        subscriptionId = transactionReceipt.events[0].args.subId
        // Fund subscription
        // Usually you had need the link token on a real network
        // on local network -> fund the subscrition without link token
        await VRF2CordinatorV2Mock.fundSubscription(subscriptionId, VRF_SUB_FUND_AMOUNT)
    } else {
        vrfCoordinatorV2Address = networkConfig[chainId]["vrfCoordinator"]
        subscriptionId = networkConfig[chainId]["subscriptionid"]
    }

    const entranceFee = networkConfig[chainId]["entranceFee"]
    const gasLane = networkConfig[chainId]["gasLane"]
    const gasLimit = networkConfig[chainId]["callbackGasLimit"]
    const intervel = networkConfig[chainId]["intervel"]

    const args = [vrfCoordinatorV2Address, entranceFee, gasLane, subscriptionId, gasLimit, intervel]
    const raffle = await deploy("Raffle", {
        from: deployer,
        args: args,
        log: true,
        waitConfirmations: network.config.blockConfirmations || 1,
    })

    if(!developmenChain.includes(network.name) && process.env.ETHERSCAN_API){
        log("Verifying.....")
        verify(raffle.address,args)
        log("-----------------------------------------")
    }
}

module.exports.tags = ["all","raffle"]
`

**Comment by Plycedes** [comment]
I have the same issue. Have you found a solution??

**Comment by coderharsx1122** [comment]
> I have the same issue. Have you found a solution??

Not yet. 
Trying to solve.

**Comment by coderharsx1122** [comment]
> I have the same issue. Have you found a solution??

Well half of the problem get solved

 **we can use this  syntax to extract subscriptionId**
```javascript
 subscriptionId = transactionReceipt.logs[0].args.subId
```
**instead of this syntax** 
```js   
subscriptionId = transactionReceipt.events[0].args.subId 
```

#### but still getting this error

```shell
 Error: Transaction reverted: function call to a non-contract account
    at Raffle.performUpkeep (contracts/Raffle.sol:128)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at HardhatNode._mineBlockWithPendingTxs (node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:1840:23)
    at HardhatNode.mineBlock (node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:517:16)
    at EthModule._sendTransactionAndReturnHash (node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:1532:18)
    at HardhatNetworkProvider.request (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:123:18)
    at HardhatEthersSigner.sendTransaction (node_modules/@nomicfoundation/hardhat-ethers/src/signers.ts:125:18)
    at send (node_modules/ethers/src.ts/contract/contract.ts:299:20)
  
```

**Comment by coderharsx1122** [comment]
> I have the same issue. Have you found a solution??

I have got the solution visit -> [solution](https://github.com/smartcontractkit/full-blockchain-solidity-course-js/discussions/6000#discussioncomment-6715227)

You can visit the github repo for the code [repo](https://github.com/coderharsx1122/smartcontract-lottery-fcc)

**Comment by dustinstacy** [comment]
> I have got the solution visit -> [solution](https://github.com/smartcontractkit/full-blockchain-solidity-course-js/discussions/6000#discussioncomment-6715227)
> 
> You can visit the github repo for the code [repo](https://github.com/coderharsx1122/smartcontract-lottery-fcc)

Great job @coderharsx1122!  This solution worked for me without using ethers v6 or Typescript.

 If you find yourself in the group attempting to use the current ethers library  as well as converting Typescript like myself (and why would you because it's a debuggers nightmare!), I believe I came across a solution.

As for the initial error of :

_ERROR_ processing /root/hardhat-fcc/hardhat-smartcontract-lottery-fcc/deploy/01-deploy-raffle.js: TypeError: Cannot read properties of undefined (reading '0')

This occurs because the `transcationReciept` object does not contain an `events` array. Instead what we are going to look at is the `logs` array. 

Following the logic of Patrick's discussion on Events, and in particular the one emitted by the `createSubscription()` function which we call  and generate our `transactionResponse` from, we see that the `SubscriptionCreated()` event logs the `s_currentSubId`:

```solidity
  function createSubscription() external override returns (uint64 _subId) {
    s_currentSubId++;
    s_subscriptions[s_currentSubId] = Subscription({owner: msg.sender, balance: 0});
    emit SubscriptionCreated(s_currentSubId, msg.sender); // **THIS LINE**
    return s_currentSubId;
  }
```

Now when we look at the `SubscriptionCreated()` event, we find that the subId is indeed indexed:
```solidity
  event SubscriptionCreated(uint64 indexed subId, address owner);
```
Using what we know now about this event, we know that the value emitted will be stored in `topics` since it was indexed. Sure enough we see on the logs object that topics does exist:

```
[
  EventLog {
    provider: HardhatEthersProvider {
      _hardhatProvider: [LazyInitializationProviderAdapter],
      _networkName: 'hardhat',
      _blockListeners: [],
      _transactionHashListeners: Map(0) {},
      _eventListeners: []
    },
    transactionHash: '0x88aa88df59f71d37e77fbaee3a34467d7191d4c7d2450e85b5cffe5d87edd4af',
    blockHash: '0x3a3774758faec2ac9cd5aee081ac7f9d68b773037dfeb8b1768ab023976e27f8',
    blockNumber: 2,
    removed: undefined,
    address: '0x5FbDB2315678afecb367f032d93F642f64180aa3',
    data: '0x000000000000000000000000f39fd6e51aad88f6f4ce6ab8827279cfffb92266',
    topics: [
      '0x464722b4166576d3dcbba877b999bc35cf911f4eaf434b7eba68fa113951d0bf',
      '0x0000000000000000000000000000000000000000000000000000000000000001'
    ],
    index: 0,
    transactionIndex: 0,
    interface: Interface {
      fragments: [Array],
      deploy: [ConstructorFragment],
      fallback: null,
      receive: false
    },
    fragment: EventFragment {
      type: 'event',
      inputs: [Array],
      name: 'SubscriptionCreated',
      anonymous: false
    },
    args: Result(2) [ 1n, '0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266' ]
  }
]
```

Now we see two values in the `topics` array. The first appears to be an address of sorts and if anyone could shed light on where that is being emitted from I am certainly curious. The next would appear to be the ` _subId ` we are looking for! I have further confidence that this holds true as when you look at the `createSubscription()` function, it's merely incrementing the s_currentSubId stored as a state variable, so since this is a mock deployment we should be on `s_currentSubId`  "1" or in this case "0x0000000000000000000000000000000000000000000000000000000000000001".

All that being said, dropping this line of code
```solidity
subscriptionId = transactionReceipt!.logs[0].topics[1]
```

In place of this one 
```solidity
subscriptionId = transactionReceipt.events[0].args.subId
```

Should do the trick!

Interested to hear anybody else's results utilizing this change. I'll keep this updated if this triggers any further issues down the line (as they usually do). 

Also, would love to connect with anyone else looking to work through this tutorial with the updated ethers library and TS as I'm sure there are plenty of opportunities to troubleshoot.

**Comment by praisezee** [comment]
Found a solution. I added the gasLane value to the hardhat chainId in the hardhat-helper-config.js

**Comment by danielvichinyan** [comment]
Use this:
`subscriptionId = txReceipt.logs[0].topics[1];`
instead of this:
`subscriptionId = transactionReceipt.events[0].args.subId;`
