### ISSUE TITLE
unit test fail

### ISSUE THREAD

**Issue by ufoqhmdt** [PatrickAlphaC/hardhat-smartcontract-lottery-fcc#36]
I clone this repo，then i run unit test，I got error：
```
Raffle Unit Tests
    constructor
31337
      ✔ intitiallizes the raffle correctly
    enterRaffle
      ✔ reverts when you don't pay enough
      ✔ records player when they enter
      ✔ emits event on enter
      1) doesn't allow entrance when raffle is calculating
    checkUpkeep
      ✔ returns false if people haven't sent any ETH
      2) returns false if raffle isn't open
      ✔ returns false if enough time hasn't passed
      ✔ returns true if enough time has passed, has players, eth, and is open
    performUpkeep
      3) can only run if checkupkeep is true
      ✔ reverts if checkup is false
      4) updates the raffle state and emits a requestId
    fulfillRandomWords
      ✔ can only be called after performupkeep
      5) picks a winner, resets, and sends money


  9 passing (3m)
  5 failing

  **1) Raffle Unit Tests
       enterRaffle
         doesn't allow entrance when raffle is calculating:
     Error: VM Exception while processing transaction: reverted with custom error 'InvalidConsumer()'
    at VRFCoordinatorV2Mock.onlyValidConsumer (@chainlink/contracts/src/v0.8/mocks/VRFCoordinatorV2Mock.sol:72)
    at VRFCoordinatorV2Mock.requestRandomWords (@chainlink/contracts/src/v0.8/mocks/VRFCoordinatorV2Mock.sol:147)
    at Raffle.performUpkeep (contracts/Raffle.sol:127)
    at async HardhatNode._mineBlockWithPendingTxs (node_modules/.pnpm/hardhat@2.10.1_6oasmw356qmm23djlsjgkwvrtm/node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:1773:23)
    at async HardhatNode.mineBlock (node_modules/.pnpm/hardhat@2.10.1_6oasmw356qmm23djlsjgkwvrtm/node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:466:16)
    at async EthModule._sendTransactionAndReturnHash (node_modules/.pnpm/hardhat@2.10.1_6oasmw356qmm23djlsjgkwvrtm/node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:1504:18)
    at async HardhatNetworkProvider.request (node_modules/.pnpm/hardhat@2.10.1_6oasmw356qmm23djlsjgkwvrtm/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:118:18)
    at async EthersProviderWrapper.send (node_modules/.pnpm/hardhat-deploy-ethers@0.3.0-beta.13_72jgnctblym52z6vqt46lbuldu/node_modules/hardhat-deploy-ethers/src/internal/ethers-provider-wrapper.ts:13:20)
  

  2) Raffle Unit Tests
       checkUpkeep
         returns false if raffle isn't open:
     Error: VM Exception while processing transaction: reverted with custom error 'InvalidConsumer()'
    at VRFCoordinatorV2Mock.onlyValidConsumer (@chainlink/contracts/src/v0.8/mocks/VRFCoordinatorV2Mock.sol:72)
    at VRFCoordinatorV2Mock.requestRandomWords (@chainlink/contracts/src/v0.8/mocks/VRFCoordinatorV2Mock.sol:147)
    at Raffle.performUpkeep (contracts/Raffle.sol:127)
    at async HardhatNode._mineBlockWithPendingTxs (node_modules/.pnpm/hardhat@2.10.1_6oasmw356qmm23djlsjgkwvrtm/node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:1773:23)
    at async HardhatNode.mineBlock (node_modules/.pnpm/hardhat@2.10.1_6oasmw356qmm23djlsjgkwvrtm/node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:466:16)
    at async EthModule._sendTransactionAndReturnHash (node_modules/.pnpm/hardhat@2.10.1_6oasmw356qmm23djlsjgkwvrtm/node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:1504:18)
    at async HardhatNetworkProvider.request (node_modules/.pnpm/hardhat@2.10.1_6oasmw356qmm23djlsjgkwvrtm/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:118:18)
    at async EthersProviderWrapper.send (node_modules/.pnpm/hardhat-deploy-ethers@0.3.0-beta.13_72jgnctblym52z6vqt46lbuldu/node_modules/hardhat-deploy-ethers/src/internal/ethers-provider-wrapper.ts:13:20)
  

  3) Raffle Unit Tests
       performUpkeep
         can only run if checkupkeep is true:
     Error: VM Exception while processing transaction: reverted with custom error 'InvalidConsumer()'
    at VRFCoordinatorV2Mock.onlyValidConsumer (@chainlink/contracts/src/v0.8/mocks/VRFCoordinatorV2Mock.sol:72)
    at VRFCoordinatorV2Mock.requestRandomWords (@chainlink/contracts/src/v0.8/mocks/VRFCoordinatorV2Mock.sol:147)
    at Raffle.performUpkeep (contracts/Raffle.sol:127)
    at async HardhatNode._mineBlockWithPendingTxs (node_modules/.pnpm/hardhat@2.10.1_6oasmw356qmm23djlsjgkwvrtm/node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:1773:23)
    at async HardhatNode.mineBlock (node_modules/.pnpm/hardhat@2.10.1_6oasmw356qmm23djlsjgkwvrtm/node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:466:16)
    at async EthModule._sendTransactionAndReturnHash (node_modules/.pnpm/hardhat@2.10.1_6oasmw356qmm23djlsjgkwvrtm/node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:1504:18)
    at async HardhatNetworkProvider.request (node_modules/.pnpm/hardhat@2.10.1_6oasmw356qmm23djlsjgkwvrtm/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:118:18)
    at async EthersProviderWrapper.send (node_modules/.pnpm/hardhat-deploy-ethers@0.3.0-beta.13_72jgnctblym52z6vqt46lbuldu/node_modules/hardhat-deploy-ethers/src/internal/ethers-provider-wrapper.ts:13:20)
  

  4) Raffle Unit Tests
       performUpkeep
         updates the raffle state and emits a requestId:
     Error: VM Exception while processing transaction: reverted with custom error 'InvalidConsumer()'
    at VRFCoordinatorV2Mock.onlyValidConsumer (@chainlink/contracts/src/v0.8/mocks/VRFCoordinatorV2Mock.sol:72)
    at VRFCoordinatorV2Mock.requestRandomWords (@chainlink/contracts/src/v0.8/mocks/VRFCoordinatorV2Mock.sol:147)
    at Raffle.performUpkeep (contracts/Raffle.sol:127)
    at async HardhatNode._mineBlockWithPendingTxs (node_modules/.pnpm/hardhat@2.10.1_6oasmw356qmm23djlsjgkwvrtm/node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:1773:23)
    at async HardhatNode.mineBlock (node_modules/.pnpm/hardhat@2.10.1_6oasmw356qmm23djlsjgkwvrtm/node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:466:16)
    at async EthModule._sendTransactionAndReturnHash (node_modules/.pnpm/hardhat@2.10.1_6oasmw356qmm23djlsjgkwvrtm/node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:1504:18)
    at async HardhatNetworkProvider.request (node_modules/.pnpm/hardhat@2.10.1_6oasmw356qmm23djlsjgkwvrtm/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:118:18)
    at async EthersProviderWrapper.send (node_modules/.pnpm/hardhat-deploy-ethers@0.3.0-beta.13_72jgnctblym52z6vqt46lbuldu/node_modules/hardhat-deploy-ethers/src/internal/ethers-provider-wrapper.ts:13:20)
  

  5) Raffle Unit Tests
       fulfillRandomWords
         picks a winner, resets, and sends money:
     Error: Timeout of 200000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/Users/sh06010ml2/Documents/workspaces/learns/lottery-test/test/unit/Raffle.test.ts)
      at listOnTimeout (node:internal/timers:559:17)
      at processTimers (node:internal/timers:502:7)**


```

**Comment by tujigogo** [comment]
same here i got same error "Error: VM Exception while processing transaction: reverted with custom error 'InvalidConsumer()'"

**Comment by OmBayus** [comment]
Change @chainlink/contracts/src/v0.8/mocks/VRFCoordinatorV2Mock.sol with this

```
// SPDX-License-Identifier: MIT
// A mock for testing code that relies on VRFCoordinatorV2.
pragma solidity ^0.8.0;

import "../interfaces/LinkTokenInterface.sol";
import "../interfaces/VRFCoordinatorV2Interface.sol";
import "../VRFConsumerBaseV2.sol";

contract VRFCoordinatorV2Mock is VRFCoordinatorV2Interface {
  uint96 public immutable BASE_FEE;
  uint96 public immutable GAS_PRICE_LINK;

  error InvalidSubscription();
  error InsufficientBalance();
  error MustBeSubOwner(address owner);

  event RandomWordsRequested(
    bytes32 indexed keyHash,
    uint256 requestId,
    uint256 preSeed,
    uint64 indexed subId,
    uint16 minimumRequestConfirmations,
    uint32 callbackGasLimit,
    uint32 numWords,
    address indexed sender
  );
  event RandomWordsFulfilled(uint256 indexed requestId, uint256 outputSeed, uint96 payment, bool success);
  event SubscriptionCreated(uint64 indexed subId, address owner);
  event SubscriptionFunded(uint64 indexed subId, uint256 oldBalance, uint256 newBalance);
  event SubscriptionCanceled(uint64 indexed subId, address to, uint256 amount);

  uint64 s_currentSubId;
  uint256 s_nextRequestId = 1;
  uint256 s_nextPreSeed = 100;
  struct Subscription {
    address owner;
    uint96 balance;
  }
  mapping(uint64 => Subscription) s_subscriptions; /* subId */ /* subscription */

  struct Request {
    uint64 subId;
    uint32 callbackGasLimit;
    uint32 numWords;
  }
  mapping(uint256 => Request) s_requests; /* requestId */ /* request */

  constructor(uint96 _baseFee, uint96 _gasPriceLink) {
    BASE_FEE = _baseFee;
    GAS_PRICE_LINK = _gasPriceLink;
  }

  /**
   * @notice fulfillRandomWords fulfills the given request, sending the random words to the supplied
   * @notice consumer.
   *
   * @dev This mock uses a simplified formula for calculating payment amount and gas usage, and does
   * @dev not account for all edge cases handled in the real VRF coordinator. When making requests
   * @dev against the real coordinator a small amount of additional LINK is required.
   *
   * @param _requestId the request to fulfill
   * @param _consumer the VRF randomness consumer to send the result to
   */
  function fulfillRandomWords(uint256 _requestId, address _consumer) external {
    uint256 startGas = gasleft();
    if (s_requests[_requestId].subId == 0) {
      revert("nonexistent request");
    }
    Request memory req = s_requests[_requestId];

    uint256[] memory words = new uint256[](req.numWords);
    for (uint256 i = 0; i < req.numWords; i++) {
      words[i] = uint256(keccak256(abi.encode(_requestId, i)));
    }

    VRFConsumerBaseV2 v;
    bytes memory callReq = abi.encodeWithSelector(v.rawFulfillRandomWords.selector, _requestId, words);
    (bool success, ) = _consumer.call{gas: req.callbackGasLimit}(callReq);

    uint96 payment = uint96(BASE_FEE + ((startGas - gasleft()) * GAS_PRICE_LINK));
    if (s_subscriptions[req.subId].balance < payment) {
      revert InsufficientBalance();
    }
    s_subscriptions[req.subId].balance -= payment;
    delete (s_requests[_requestId]);
    emit RandomWordsFulfilled(_requestId, _requestId, payment, success);
  }

  /**
   * @notice fundSubscription allows funding a subscription with an arbitrary amount for testing.
   *
   * @param _subId the subscription to fund
   * @param _amount the amount to fund
   */
  function fundSubscription(uint64 _subId, uint96 _amount) public {
    if (s_subscriptions[_subId].owner == address(0)) {
      revert InvalidSubscription();
    }
    uint96 oldBalance = s_subscriptions[_subId].balance;
    s_subscriptions[_subId].balance += _amount;
    emit SubscriptionFunded(_subId, oldBalance, oldBalance + _amount);
  }

  function requestRandomWords(
    bytes32 _keyHash,
    uint64 _subId,
    uint16 _minimumRequestConfirmations,
    uint32 _callbackGasLimit,
    uint32 _numWords
  ) external override returns (uint256) {
    if (s_subscriptions[_subId].owner == address(0)) {
      revert InvalidSubscription();
    }

    uint256 requestId = s_nextRequestId++;
    uint256 preSeed = s_nextPreSeed++;

    s_requests[requestId] = Request({subId: _subId, callbackGasLimit: _callbackGasLimit, numWords: _numWords});

    emit RandomWordsRequested(
      _keyHash,
      requestId,
      preSeed,
      _subId,
      _minimumRequestConfirmations,
      _callbackGasLimit,
      _numWords,
      msg.sender
    );
    return requestId;
  }

  function createSubscription() external override returns (uint64 _subId) {
    s_currentSubId++;
    s_subscriptions[s_currentSubId] = Subscription({owner: msg.sender, balance: 0});
    emit SubscriptionCreated(s_currentSubId, msg.sender);
    return s_currentSubId;
  }

  function getSubscription(uint64 _subId)
    external
    view
    override
    returns (
      uint96 balance,
      uint64 reqCount,
      address owner,
      address[] memory consumers
    )
  {
    if (s_subscriptions[_subId].owner == address(0)) {
      revert InvalidSubscription();
    }
    return (s_subscriptions[_subId].balance, 0, s_subscriptions[_subId].owner, new address[](0));
  }

  function cancelSubscription(uint64 _subId, address _to) external override onlySubOwner(_subId) {
    emit SubscriptionCanceled(_subId, _to, s_subscriptions[_subId].balance);
    delete (s_subscriptions[_subId]);
  }

  modifier onlySubOwner(uint64 _subId) {
    address owner = s_subscriptions[_subId].owner;
    if (owner == address(0)) {
      revert InvalidSubscription();
    }
    if (msg.sender != owner) {
      revert MustBeSubOwner(owner);
    }
    _;
  }

  function getRequestConfig()
    external
    pure
    override
    returns (
      uint16,
      uint32,
      bytes32[] memory
    )
  {
    return (3, 2000000, new bytes32[](0));
  }

  function addConsumer(uint64 _subId, address _consumer) external pure override {
    revert("not implemented");
  }

  function removeConsumer(uint64 _subId, address _consumer) external pure override {
    revert("not implemented");
  }

  function requestSubscriptionOwnerTransfer(uint64 _subId, address _newOwner) external pure override {
    revert("not implemented");
  }

  function acceptSubscriptionOwnerTransfer(uint64 _subId) external pure override {
    revert("not implemented");
  }

  function pendingRequestExists(uint64 subId) public view override returns (bool) {
    revert("not implemented");
  }
}
```

**Comment by PavelNaydanov** [comment]
You need to add consumer for VRFCoordinatorV2Mock.

`if (developmentChains.includes(network.name)) {
    await vrfCoordinatorV2Mock.addConsumer(subscriptionId, raffle.address);
  }`

Full example 01-deploy-raffle.js
`const {
  network,
  ethers
} = require("hardhat");
const {
    networkConfig,
    developmentChains,
} = require("../helper-hardhat-config");
const { verify } = require("../utils/verify");

const VRF_SUB_FUND_AMOUNT = ethers.utils.parseEther("30");

module.exports = async function ({ getNamedAccounts, deployments }) {
  const { deploy, log } = deployments;
  const { deployer } = await getNamedAccounts();
  const chainId = network.config.chainId;

  let vrfCoordinatorV2Mock;
  let vrfCoordinatorV2addres;
  let subscriptionId;

  if (developmentChains.includes(network.name)) {
    vrfCoordinatorV2Mock = await ethers.getContract('VRFCoordinatorV2Mock');
    vrfCoordinatorV2addres = vrfCoordinatorV2Mock.address;

    const transactionResponse = await vrfCoordinatorV2Mock.createSubscription();
    const transactionReceipt = await transactionResponse.wait(1)
    subscriptionId = transactionReceipt.events[0].args.subId

    vrfCoordinatorV2Mock.fundSubscription(subscriptionId, VRF_SUB_FUND_AMOUNT);
  }
  else {
    vrfCoordinatorV2addres = networkConfig[chainId]["vrfCoordinatorV2"];
    subscriptionId = networkConfig[chainId]["subscriptionId"];
  }

  const entranceFee = networkConfig[chainId]["entranceFee"];
  const gasLane = networkConfig[chainId]["gasLane"];
  const callbackGasLimit = networkConfig[chainId]["callbackGasLimit"];
  const interval = networkConfig[chainId]["interval"];

  const args = [
    vrfCoordinatorV2addres,
    entranceFee,
    gasLane,
    subscriptionId,
    callbackGasLimit,
    interval
  ];

  const raffle = await deploy('Raffle', {
    from: deployer,
    args,
    log: true,
    waitConfirmations: network.config.blockConfirmations || 1
  });

  log(`Raffle contract is deployed: ${raffle.address}`);

  if (developmentChains.includes(network.name)) {
    await vrfCoordinatorV2Mock.addConsumer(subscriptionId, raffle.address);

    log('Consumer is added');
  }

  if (
    !developmentChains.includes(network.name) &&
    process.env.ETHERSCAN_API_KEY
  ) {
    await verify(fundMe.address, args);
  }

  log("----------------------------------");
}

module.exports.tags = ["all", "raffle"];`

This will be fixed.

**Comment by deeptshukla** [comment]
@ufoqhmdt , as done manually for testnet (Look into https://youtu.be/rdJ5d8j1RCg by chainlink)
, we have to create a VRFCoordinatorV2 (VRFCoordinatorV2Mock in case of local testing), fund it and then have to add our contract to allowedConsumers list.

Following code we should add after deploying our raffle smart contract
```solidity
if (developmentChains.includes(network.name)) {
    await vrfCoordinatorV2Mock.addConsumer(subscriptionId, raffle.address);

    log('Consumer is added');
  }
```

**Comment by PatrickAlphaC** [comment]
Unit tests are passing for me:

```
git clone https://github.com/PatrickAlphaC/hardhat-smartcontract-lottery-fcc
cd hardhat-smartcontract-lottery-fcc
yarn
yarn hardhat test
```

What are you using to run tests?

**Comment by Nikhil-blockchain** [comment]
Tried Everything but this error persisits. Problem is probably
const accounts = await ethers.getSigners()

5) Raffle Unit Tests
       fulfillRandomWords
         picks a winner, resets, and sends money:
     Error: Timeout of 200000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/Users/sh06010ml2/Documents/workspaces/learns/lottery-test/test/unit/Raffle.test.ts)
      at listOnTimeout (node:internal/timers:559:17)
      at processTimers (node:internal/timers:502:7)**
