### ISSUE TITLE
Unexpepected error when i tried to deploy.

### ISSUE THREAD

**Issue by Puchacz1** [PatrickAlphaC/hardhat-smartcontract-lottery-fcc#60]
Code 01-deploy-raffle.js:

const { getNamedAccounts, network, ethers } = require("hardhat")
const { developmentChains, networkConfig } = require("../helper-hardhat-config")
const { verify } = require("../helper-hardhat-config")

const VRF_SUB_FUND_AMOUNT = ethers.utils.parseEther("2")

module.exports = async function ({ getNamedAccount, deployments }) {
    const { deploy, log } = deployments
    const { deployer } = await getNamedAccounts()
    const chainId = network.config.chainId
    let vrfCoordinatorV2Address, subscriptionId, vrfCoordinatorV2Mock

    if (chainId == 31337) {
        const vrfCoordinatorV2Mock = await ethers.getContract(
            "VRFCoordinatorV2Mock"
        )
        vrfCoordinatorV2Address = vrfCoordinatorV2Mock.address
        const transactionResponse =
            await vrfCoordinatorV2Mock.createSubscription()
        const transactionReceipt = await transactionResponse.wait(1)
        subscriptionId = transactionReceipt.events[0].args.subId
        await vrfCoordinatorV2Mock.fundSubscription(
            subscriptionId,
            VRF_SUB_FUND_AMOUNT
        )
    } else {
        vrfCoordinatorV2Address = networkConfig[chainId]["vrfCoordinatorV2"]
        subscriptionId = networkConfig[chainId]["subscriptionId"]
    }
    const entranceFee = networkConfig[chainId]["entranceFee"]
    const gasLane = networkConfig[chainId]["gasLane"]
    const callbackGasLimit = networkConfig[chainId]["callbackGasLimit"]
    const interval = networkConfig[chainId]["interval"]

    const args = [
        vrfCoordinatorV2Address,
        entranceFee,
        gasLane,
        subscriptionId,
        callbackGasLimit,
        interval,
    ]
    const raffle = await deploy("Raffle", {
        from: deployer,
        args: args,
        log: true,
        waitConfirmations: network.config.blockConfirmations || 1,
    })

    if (
        !developmentChain.includes(network.name) &&
        process.env.ETHERSCAN_API_KEY
    ) {
        log("Verifying...")
        await verify(raffle.address, args)
    }
    log("________________________")
}

module.exports.tags = ["all", "raffle"]

Error:
yarn run v1.22.15
warning package.json: No license field
$ /home/filip/hardhat-smartcontract-lottery/node_modules/.bin/hardhat deploy
Nothing to compile
Local network detected! Deploying mocks...
deploying "VRFCoordinatorV2Mock" (tx: 0x568782af0a079d0bc6f4e4e40b0e5953a1299aa5fd7a0eccc01ff0568a422e43)...: deployed at 0x5FbDB2315678afecb367f032d93F642f64180aa3 with 1803090 gas
Mocks Deployed!
_____________________________
deploying "Raffle" (tx: 0xf759543e44e0ced2da1f7eeaffcdcf790bff3abf197a49669f9d872422b0ccc0)...: deployed at 0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9 with 1197444 gas
An unexpected error occurred:

Error: ERROR processing /home/filip/hardhat-smartcontract-lottery/deploy/01-deploy-raffle.js:
ReferenceError: developmentChain is not defined
    at Object.module.exports [as func] (/home/filip/hardhat-smartcontract-lottery/deploy/01-deploy-raffle.js:50:5)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at runNextTicks (node:internal/process/task_queues:65:3)
    at listOnTimeout (node:internal/timers:528:9)
    at processTimers (node:internal/timers:502:7)
    at DeploymentsManager.executeDeployScripts (/home/filip/hardhat-smartcontract-lottery/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1219:22)
    at DeploymentsManager.runDeploy (/home/filip/hardhat-smartcontract-lottery/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1052:5)
    at SimpleTaskDefinition.action (/home/filip/hardhat-smartcontract-lottery/node_modules/hardhat-deploy/src/index.ts:438:5)
    at Environment._runTaskDefinition (/home/filip/hardhat-smartcontract-lottery/node_modules/hardhat/src/internal/core/runtime-environment.ts:219:14)
    at Environment.run (/home/filip/hardhat-smartcontract-lottery/node_modules/hardhat/src/internal/core/runtime-environment.ts:131:14)
    at DeploymentsManager.executeDeployScripts (/home/filip/hardhat-smartcontract-lottery/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1222:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at runNextTicks (node:internal/process/task_queues:65:3)
    at listOnTimeout (node:internal/timers:528:9)
    at processTimers (node:internal/timers:502:7)
    at DeploymentsManager.runDeploy (/home/filip/hardhat-smartcontract-lottery/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1052:5)
    at SimpleTaskDefinition.action (/home/filip/hardhat-smartcontract-lottery/node_modules/hardhat-deploy/src/index.ts:438:5)
    at Environment._runTaskDefinition (/home/filip/hardhat-smartcontract-lottery/node_modules/hardhat/src/internal/core/runtime-environment.ts:219:14)
    at Environment.run (/home/filip/hardhat-smartcontract-lottery/node_modules/hardhat/src/internal/core/runtime-environment.ts:131:14)
    at SimpleTaskDefinition.action (/home/filip/hardhat-smartcontract-lottery/node_modules/hardhat-deploy/src/index.ts:584:32)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by byte14** [comment]
`
if (
    !developmentChain.includes(network.name) &&
    process.env.ETHERSCAN_API_KEY
) {
    log("Verifying...")
    await verify(raffle.address, args)
}`

There's a typo, you forgot s at the end of developmentChain.

**Comment by Puchacz1** [comment]
thank u so much
