### ISSUE TITLE
Error: value out-of-bounds (argument="callbackGasLimit", value={"type":"BigNumber","hex":"0x2386f26fc10000"}, code=INVALID_ARGUMENT, version=abi/5.7.0)

### ISSUE THREAD

**Issue by Nurnberg-Meistersinger** [PatrickAlphaC/hardhat-smartcontract-lottery-fcc#94]
### Description

Hey guys, I can't solve this issue by myself, currently asking for your help. 

I also tried to play with `callbackGasLimit` value using `3000000`, `2500` and `50000`, but got the same result.

I will be grateful for your advice!

### **Error output**
```
Nothing to compile
Local network detected! Deploying mocks...
deploying "VRFCoordinatorV2Mock" (tx: 0x11b9dfa83e5a81e783d8d818bd6499fa1504a937113eca5f07b8cfafe70751ea)...: deployed at 0x5FbDB2315678afecb367f032d93F642f64180aa3 with 1797707 gas
Mocks Deployed!
------------------------------------------
You are deploying to a local network, you'll need a local network running to interact
Please run `yarn hardhat console --network localhost` to interact with the deployed smart contracts!
------------------------------------------
------------------------------------------
An unexpected error occurred:

Error: ERROR processing /home/hilaymanai-133676/Work/hh-fcc/hardhat-lottery-fcc/deploy/01-deploy-raffle.js:
Error: value out-of-bounds (argument="callbackGasLimit", value={"type":"BigNumber","hex":"0x2386f26fc10000"}, code=INVALID_ARGUMENT, version=abi/5.7.0)
    at Logger.makeError (/home/hilaymanai-133676/Work/hh-fcc/hardhat-lottery-fcc/node_modules/@ethersproject/logger/src.ts/index.ts:269:28)
    at Logger.throwError (/home/hilaymanai-133676/Work/hh-fcc/hardhat-lottery-fcc/node_modules/@ethersproject/logger/src.ts/index.ts:281:20)
    at Logger.throwArgumentError (/home/hilaymanai-133676/Work/hh-fcc/hardhat-lottery-fcc/node_modules/@ethersproject/logger/src.ts/index.ts:285:21)
    at NumberCoder.Coder._throwError (/home/hilaymanai-133676/Work/hh-fcc/hardhat-lottery-fcc/node_modules/@ethersproject/abi/src.ts/coders/abstract-coder.ts:68:16)
    at NumberCoder.encode (/home/hilaymanai-133676/Work/hh-fcc/hardhat-lottery-fcc/node_modules/@ethersproject/abi/src.ts/coders/number.ts:35:18)
    at /home/hilaymanai-133676/Work/hh-fcc/hardhat-lottery-fcc/node_modules/@ethersproject/abi/src.ts/coders/array.ts:71:19
    at Array.forEach (<anonymous>)
    at pack (/home/hilaymanai-133676/Work/hh-fcc/hardhat-lottery-fcc/node_modules/@ethersproject/abi/src.ts/coders/array.ts:54:12)
    at TupleCoder.encode (/home/hilaymanai-133676/Work/hh-fcc/hardhat-lottery-fcc/node_modules/@ethersproject/abi/src.ts/coders/tuple.ts:54:20)
    at AbiCoder.encode (/home/hilaymanai-133676/Work/hh-fcc/hardhat-lottery-fcc/node_modules/@ethersproject/abi/src.ts/abi-coder.ts:111:15)
    at DeploymentsManager.executeDeployScripts (/home/hilaymanai-133676/Work/hh-fcc/hardhat-lottery-fcc/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1222:19)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at runNextTicks (node:internal/process/task_queues:64:3)
    at listOnTimeout (node:internal/timers:533:9)
    at processTimers (node:internal/timers:507:7)
    at DeploymentsManager.runDeploy (/home/hilaymanai-133676/Work/hh-fcc/hardhat-lottery-fcc/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1052:5)
    at SimpleTaskDefinition.action (/home/hilaymanai-133676/Work/hh-fcc/hardhat-lottery-fcc/node_modules/hardhat-deploy/src/index.ts:438:5)
    at Environment._runTaskDefinition (/home/hilaymanai-133676/Work/hh-fcc/hardhat-lottery-fcc/node_modules/hardhat/src/internal/core/runtime-environment.ts:219:14)
    at Environment.run (/home/hilaymanai-133676/Work/hh-fcc/hardhat-lottery-fcc/node_modules/hardhat/src/internal/core/runtime-environment.ts:131:14)
    at SimpleTaskDefinition.action (/home/hilaymanai-133676/Work/hh-fcc/hardhat-lottery-fcc/node_modules/hardhat-deploy/src/index.ts:584:32)
```
### **`01-deploy-raffle.js` code**

```javascript
const { network, ethers } = require("hardhat")
const {
    networkConfig,
    developmentChains,
    VERIFICATION_BLOCK_CONFIRMATIONS,
} = require("../helper-hardhat-config")
const { verify } = require("../utils/verify")

const FUND_AMOUNT = ethers.utils.parseEther("1")

module.exports = async ({ getNamedAccounts, deployments }) => {
    const { deploy, log } = deployments
    const { deployer } = await getNamedAccounts()
    const chainId = network.config.chainId
    let vrfCoordinatorV2Address, subscriptionId, vrfCoordinatorV2Mock

    if (chainId == 31337) {
        // create VRFV2 Subscription
        vrfCoordinatorV2Mock = await ethers.getContract("VRFCoordinatorV2Mock")
        vrfCoordinatorV2Address = vrfCoordinatorV2Mock.address
        const transactionResponse = await vrfCoordinatorV2Mock.createSubscription()
        const transactionReceipt = await transactionResponse.wait()
        subscriptionId = transactionReceipt.events[0].args.subId
        // Fund the subscription
        // Our mock makes it so we don't actually have to worry about sending fund
        await vrfCoordinatorV2Mock.fundSubscription(subscriptionId, FUND_AMOUNT)
    } else {
        vrfCoordinatorV2Address = networkConfig[chainId]["vrfCoordinatorV2"]
        subscriptionId = networkConfig[chainId]["subscriptionId"]
    }
    const waitBlockConfirmations = developmentChains.includes(network.name)
        ? 1
        : VERIFICATION_BLOCK_CONFIRMATIONS

    log("----------------------------------------------------")
    const arguments = [
        vrfCoordinatorV2Address,
        subscriptionId,
        networkConfig[chainId]["gasLane"],
        networkConfig[chainId]["keepersUpdateInterval"],
        networkConfig[chainId]["raffleEntranceFee"],
        networkConfig[chainId]["callbackGasLimit"],
    ]
    const raffle = await deploy("Raffle", {
        from: deployer,
        args: arguments,
        log: true,
        waitConfirmations: waitBlockConfirmations,
    })

    // Verify the deployment
    if (!developmentChains.includes(network.name) && process.env.ETHERSCAN_API_KEY) {
        log("Verifying...")
        await verify(raffle.address, arguments)
    }

    log("Enter lottery with command:")
    const networkName = network.name == "hardhat" ? "localhost" : network.name
    log(`yarn hardhat run scripts/enterRaffle.js --network ${networkName}`)
    log("----------------------------------------------------")
}

module.exports.tags = ["all", "raffle"]
```

### `helper-hardhat-config.js` code

```javascript
const { ethers } = require("hardhat");

const networkConfig = {
  default: {
    name: "hardhat",
    keepersUpdateInterval: "30",
  },
  5: {
    name: "goerli",
    subscriptionId: "6926",
    gasLane: "0x79d3d8832d904592c0bf9818b621522c988bb8b0c05cdc3b15aea1b6e8db0c15",
    keepersUpdateInterval: "30",
    raffleEntranceFee: ethers.utils.parseEther("0.01"),
    callbackGasLimit: "500000",
    vrfCoordinatorV2: "0x2Ca8E0C643bDe4C2E08ab1fA0da3401AdAD7734D",
},
  80001: {
    name: "mumbai",
    vrfCoordinatorV2: "0x7a1BaC17Ccc5b313516C5E16fb24f7659aA5ebed",
    raffleEntranceFee: ethers.utils.parseEther("0.01"),
    gasLane:
      "0x4b09e658ed251bcafeebbc69400383d49f344ace09b9576fe248bb02c003fe9f",
    subscriptionId: "1874",
    callbackGasLimit: "500000",
    keepersUpdateInterval: "30",
  },
  31337: {
    name: "localhost",
    raffleEntranceFee: ethers.utils.parseEther("0.01"),
    gasLane:
      "0xd89b2bf150e3b9e13446986e571fb9cab24b13cea0a43ea20a6049a85cc807cc",
    subscriptionId: "1874",
    callbackGasLimit: "500000",
    keepersUpdateInterval: "30",
  },
};

const developmentChains = ["hardhat", "localhost"];
const VERIFICATION_BLOCK_CONFIRMATIONS = 6

module.exports = {
    networkConfig,
    developmentChains,
    VERIFICATION_BLOCK_CONFIRMATIONS,
}
```

**Comment by RyanPaulGannon** [comment]
I think this is maybe something to do with the order of your `arguments` in relation to your `raffle.sol`

Here is mine just for example, just check they're in the correct order as I think your error of `value={"type":"BigNumber"` is trying to access a different argument.

So, from my `01-deploy-lottery.ts`

```
 const args = [
    vrfCoordinatorV2Address,
    entranceFee,
    gasLane,
    subscriptionId,
    callbackGasLimit,
    interval,
  ]
```

And, my `Lottery.sol`

```
constructor(
        address vrfCoordinatorV2, // contract
        uint256 entranceFee,
        bytes32 gasLane,
        uint64 subscriptionId,
        uint32 callbackGasLimit,
        uint256 interval
    ) VRFConsumerBaseV2(vrfCoordinatorV2) {
        i_vrfCoordinator = VRFCoordinatorV2Interface(vrfCoordinatorV2);
        i_entranceFee = entranceFee;
        i_gasLane = gasLane;
        i_subscriptionId = subscriptionId;
        i_callbackGasLimit = callbackGasLimit;
        s_lotteryState = LotteryState.OPEN;
        s_lastestTimeStamp = block.timestamp;
        i_interval = interval;
    }
```

Let us know if that works

**Comment by Nurnberg-Meistersinger** [comment]
@RyanPaulGannon  you're absolutely, 100% right!🎉🎉🎉

Thank you SO MUCH. I've solved a problem.
